all:
  hosts:
  children:
    local:
      hosts: localhost
    prod:
      hosts: status.example.com
    pettracertest:
      hosts: testportal.example.com
    pettracer:
      hosts: portal.example.com:26